import type { CardData } from './types';

const SET_NAME = "AWAKENING";
const TOTAL_IN_SET = 90;

// prettier-ignore
export const MASTER_DB: CardData[] = [
  // =======================================================================
  // FEUER
  // =======================================================================
  { id: 1, set: SET_NAME, numberInSet: 1, totalInSet: TOTAL_IN_SET, name: "Inferno Drake", cost: 4, type: "Unit", element: "Feuer", rarity: "Epic", atk: 5, hp: 4, fokus: 2, text: "Beim Ausspielen: Füge allen gegnerischen Einheiten 2 Schaden zu.", img: "/cards/inferno-drake.jpg", img_hint: "inferno dragon", previewVideoUrl: "/cards/videos/inferno-drake.mp4" },
  { id: 2, set: SET_NAME, numberInSet: 2, totalInSet: TOTAL_IN_SET, name: "Gladiator", cost: 2, type: "Unit", element: "Feuer", rarity: "Uncommon", atk: 3, hp: 2, fokus: 1, text: "Wenn Gladiator angreift, fügt er dem gegnerischen Binder 1 zusätzlichen Schaden zu.", img: "/cards/gladiator.jpg", img_hint: "ash warrior", previewVideoUrl: "/cards/videos/gladiator.mp4" },
  { id: 3, set: SET_NAME, numberInSet: 3, totalInSet: TOTAL_IN_SET, name: "Ashwalker", cost: 1, type: "Unit", element: "Feuer", rarity: "Common", atk: 2, hp: 1, fokus: 1, text: "Stirbt Ashwalker, füge einem beliebigen Ziel 1 Schaden zu.", img: "/cards/ashwalker.jpg", img_hint: "ash walker", previewVideoUrl: "/cards/videos/ashwalker.mp4" },
  { id: 4, set: SET_NAME, numberInSet: 4, totalInSet: TOTAL_IN_SET, name: "Flamebounder", cost: 3, type: "Unit", element: "Feuer", rarity: "Rare", atk: 4, hp: 3, fokus: 2, text: "Solange Flamebounder angreift, erhalten alle deine Feuer-Einheiten +1 Angriff.", img: "/cards/flamebound-champion.jpg", img_hint: "flame champion", previewVideoUrl: "/cards/videos/flamebounder.mp4", keywords: { overcharge: true } },
  { id: 5, set: SET_NAME, numberInSet: 5, totalInSet: TOTAL_IN_SET, name: "Tinkerer", cost: 2, type: "Unit", element: "Feuer", rarity: "Rare", atk: 2, hp: 3, fokus: 3, text: "Aktiv (1 Fokus): Füge einer gegnerischen Einheit 2 Schaden zu.", img: "/cards/tinkerer.jpg", img_hint: "goblin tinkerer", previewVideoUrl: "/cards/videos/tinkerer.mp4" },
  { id: 6, set: SET_NAME, numberInSet: 6, totalInSet: TOTAL_IN_SET, name: "Tristan", cost: 5, type: "Unit", element: "Feuer", rarity: "Epic", atk: 6, hp: 5, fokus: 1, text: "Tristan kann nicht blocken, verursacht aber +2 Schaden am Binder, wenn ungeblockt.", img: "/cards/tristan.jpg", img_hint: "volcanic brute", previewVideoUrl: "/cards/videos/tristan.mp4" },
  { id: 7, set: SET_NAME, numberInSet: 7, totalInSet: TOTAL_IN_SET, name: "Soburin", cost: 5, type: "Unit", element: "Feuer", rarity: "Epic", atk: 5, hp: 5, fokus: 2, text: "Beim Ausspielen: Zerstöre alle gegnerischen Fallenkarten.", img: "/cards/soburin.jpg", img_hint: "fire samurai", previewVideoUrl: "/cards/videos/soburin.mp4" },
  { id: 8, set: SET_NAME, numberInSet: 8, totalInSet: TOTAL_IN_SET, name: "Kael", cost: 6, type: "Unit", element: "Feuer", rarity: "Legendary", atk: 5, hp: 5, fokus: 3, text: "Stirbt Kael, kehrt er zu Beginn deines nächsten Zuges mit 3 Verteidigung zurück.", img: "/mission/kael.jpg", img_hint: "phoenix warden", previewVideoUrl: "/cards/videos/kael-preview.mp4" },
  { id: 9, set: SET_NAME, numberInSet: 9, totalInSet: TOTAL_IN_SET, name: "Barbarossa", cost: 4, type: "Unit", element: "Feuer", rarity: "Rare", atk: 5, hp: 3, fokus: 2, text: "Wenn Barbarossa Schaden erleidet, erhält er +1 Angriff (dauerhaft).", img: "/cards/barbarossa.jpg", img_hint: "barbarian warrior", previewVideoUrl: "/cards/videos/barbarossa.mp4" },
  { id: 10, set: SET_NAME, numberInSet: 10, totalInSet: TOTAL_IN_SET, name: "Fireburst", cost: 2, type: "Spell", element: "Feuer", rarity: "Common", text: "Füge einem beliebigen Ziel 3 Schaden zu.", img: "/cards/fireburst.jpg", img_hint: "fire burst", previewVideoUrl: "/cards/videos/fireburst.mp4" },
  { id: 11, set: SET_NAME, numberInSet: 11, totalInSet: TOTAL_IN_SET, name: "Overheat", cost: 1, type: "Spell", element: "Feuer", rarity: "Common", text: "Der nächste Schadenseffekt in diesem Zug verursacht +2 zusätzlichen Schaden.", img: "/cards/overheat.jpg", img_hint: "overheat explosion", previewVideoUrl: "/cards/videos/overheat.mp4" },
  { id: 12, set: SET_NAME, numberInSet: 12, totalInSet: TOTAL_IN_SET, name: "Scorching Wave", cost: 4, type: "Spell", element: "Feuer", rarity: "Rare", text: "Füge allen Einheiten 2 Schaden zu.", img: "/cards/scorching-wave.jpg", img_hint: "scorching wave", previewVideoUrl: "/cards/videos/scorching-wave.mp4" },
  { id: 13, set: SET_NAME, numberInSet: 13, totalInSet: TOTAL_IN_SET, name: "Last Spark", cost: 3, type: "Spell", element: "Feuer", rarity: "Epic", text: "Füge einem gegnerischen Binder 4 Schaden zu. Wenn der Binder ≤5 HP hat, stattdessen 6 Schaden.", img: "/cards/last-spark.jpg", img_hint: "final spark", previewVideoUrl: "/cards/videos/last-spark.mp4" },
  { id: 14, set: SET_NAME, numberInSet: 14, totalInSet: TOTAL_IN_SET, name: "Flamethrower", cost: 2, type: "Trap", element: "Feuer", rarity: "Common", text: "Trigger: Wenn eine gegnerische Einheit angreift. Effekt: Füge der angreifenden Einheit 3 Schaden zu und beende ihren Angriff.", img: "/cards/flamethrower.jpg", img_hint: "flame snare", previewVideoUrl: "/cards/videos/flamethrower.mp4" },
  { id: 15, set: SET_NAME, numberInSet: 15, totalInSet: TOTAL_IN_SET, name: "Backdraft", cost: 3, type: "Trap", element: "Feuer", rarity: "Rare", text: "Trigger: Wenn eine deiner Einheiten stirbt. Effekt: Füge allen gegnerischen Einheiten 2 Schaden zu.", img: "/cards/backdraft.jpg", img_hint: "fire backdraft", previewVideoUrl: "/cards/videos/backdraft.mp4" },
  { id: 16, set: SET_NAME, numberInSet: 16, totalInSet: TOTAL_IN_SET, name: "Flaming Crown", cost: 1, type: "Relic", element: "Feuer", rarity: "Epic", text: "Immer wenn du Overcharge nutzt, erhalten deine Einheiten +1 Angriff bis zum Ende des Zuges.", img: "/cards/flaming-crown.jpg", img_hint: "ember core", previewVideoUrl: "/cards/videos/flaming-crown.mp4" },
  // =======================================================================
  // WASSER
  // =======================================================================
  { id: 17, set: SET_NAME, numberInSet: 17, totalInSet: TOTAL_IN_SET, name: "Ice Nomad", cost: 2, type: "Unit", element: "Wasser", rarity: "Common", atk: 2, hp: 3, fokus: 2, text: "Aktiv (2 Fokus): Erhalte für diese Runde +1 Angriff.", img: "/cards/ice-nomad.jpg", img_hint: "ice nomad", previewVideoUrl: "/cards/videos/ice-nomad.mp4" },
  { id: 18, set: SET_NAME, numberInSet: 18, totalInSet: TOTAL_IN_SET, name: "Icewalker", cost: 1, type: "Unit", element: "Wasser", rarity: "Common", atk: 1, hp: 2, fokus: 1, text: "Wenn du einen Spell wirkst, erhalte 1 Fokus auf Icewalker.", img: "/cards/icewalker.jpg", img_hint: "ice walker", previewVideoUrl: "/cards/videos/icewalker.mp4" },
  { id: 19, set: SET_NAME, numberInSet: 19, totalInSet: TOTAL_IN_SET, name: "Deepsea Guardian", cost: 3, type: "Unit", element: "Wasser", rarity: "Rare", atk: 2, hp: 5, fokus: 1, text: "Solange Deepsea Guardian im Spiel ist, erleidet dein Binder 1 weniger Schaden aus allen Quellen.", img: "/cards/deepsea-guardian.jpg", img_hint: "deepsea guardian", previewVideoUrl: "/cards/videos/deepsea-guardian.mp4" },
  { id: 20, set: SET_NAME, numberInSet: 20, totalInSet: TOTAL_IN_SET, name: "Frostveil Siren", cost: 3, type: "Unit", element: "Wasser", rarity: "Rare", atk: 3, hp: 2, fokus: 2, text: "Beim Ausspielen: Wähle eine gegnerische Einheit. Diese Einheit kann im nächsten Zug nicht angreifen.", img: "/cards/frostveil-siren.jpg", img_hint: "frost siren", previewVideoUrl: "/cards/videos/frostveil-siren.mp4" },
  { id: 21, set: SET_NAME, numberInSet: 21, totalInSet: TOTAL_IN_SET, name: "Wavecaller Oracle", cost: 4, type: "Unit", element: "Wasser", rarity: "Epic", atk: 3, hp: 4, fokus: 2, text: "Einmal pro Zug, wenn du einen Spell wirkst: Ziehe 1 Karte.", img: "/cards/wavecaller-oracle.jpg", img_hint: "wave oracle", previewVideoUrl: "/cards/videos/wavecaller-oracle.mp4" },
  { id: 22, set: SET_NAME, numberInSet: 22, totalInSet: TOTAL_IN_SET, name: "Zoa", cost: 5, type: "Unit", element: "Wasser", rarity: "Epic", atk: 5, hp: 5, fokus: 2, text: "Zoa kann zwei Einheiten gleichzeitig blocken.", img: "/cards/zoa.jpg", img_hint: "water warrior", previewVideoUrl: "/cards/videos/zoa.mp4" },
  { id: 23, set: SET_NAME, numberInSet: 23, totalInSet: TOTAL_IN_SET, name: "Mireya", cost: 6, type: "Unit", element: "Wasser", rarity: "Legendary", atk: 5, hp: 7, fokus: 2, text: "Gegnerische Einheiten mit Kosten 3 oder weniger können nicht angreifen, solange Mireya im Spiel ist.", img: "/mission/mireya.jpg", img_hint: "water mage", previewVideoUrl: "/mission/mireya.mp4" },
  { id: 24, set: SET_NAME, numberInSet: 24, totalInSet: TOTAL_IN_SET, name: "Water Elementar", cost: 5, type: "Unit", element: "Wasser", rarity: "Rare", atk: 4, hp: 5, fokus: 2, text: "Zu Beginn deines Zuges: Wähle eine gegnerische Einheit. Diese Einheit erhält –1 Angriff (dauerhaft).", img: "/cards/water-elementar.jpg", img_hint: "water elemental", previewVideoUrl: "/cards/videos/water-element.mp4" },
  { id: 25, set: SET_NAME, numberInSet: 25, totalInSet: TOTAL_IN_SET, name: "Icebound Defender", cost: 2, type: "Unit", element: "Wasser", rarity: "Uncommon", atk: 1, hp: 4, fokus: 1, text: "Icebound Defender kann beliebig viele Einheiten blocken.", img: "/cards/icebound-defender.jpg", img_hint: "ice defender", previewVideoUrl: "/cards/videos/icebound-defender.mp4" },
  { id: 26, set: SET_NAME, numberInSet: 26, totalInSet: TOTAL_IN_SET, name: "Freeze Current", cost: 2, type: "Spell", element: "Wasser", rarity: "Common", text: "Eine gegnerische Unit wird eingefroren (überspringt ihren nächsten Zug).", img: "/cards/freeze-current.jpg", img_hint: "ice spell", previewVideoUrl: "/cards/videos/freeze-current.mp4" },
  { id: 27, set: SET_NAME, numberInSet: 27, totalInSet: TOTAL_IN_SET, name: "Counterflow", cost: 3, type: "Spell", element: "Wasser", rarity: "Rare", text: "Neutralisiere einen gegnerischen Spell.", img: "/cards/counterflow.jpg", img_hint: "water vortex", previewVideoUrl: "/cards/videos/counterflow.mp4" },
  { id: 28, set: SET_NAME, numberInSet: 28, totalInSet: TOTAL_IN_SET, name: "Tidal Recall", cost: 2, type: "Spell", element: "Wasser", rarity: "Common", text: "Bringe eine gegnerische Einheit auf die Hand ihres Besitzers zurück.", img: "/cards/tidal-recall.jpg", img_hint: "water splash", previewVideoUrl: "/cards/videos/tidal-recall.mp4" },
  { id: 29, set: SET_NAME, numberInSet: 29, totalInSet: TOTAL_IN_SET, name: "Calm the Depths", cost: 4, type: "Spell", element: "Wasser", rarity: "Rare", text: "Stelle deinem Binder 4 Lebenspunkte wieder her und ziehe 1 Karte.", img: "/cards/calm-the-depths.jpg", img_hint: "calm water", previewVideoUrl: "/cards/videos/calm-the-depths.mp4" },
  { id: 30, set: SET_NAME, numberInSet: 30, totalInSet: TOTAL_IN_SET, name: "Sudden Undertow", cost: 2, type: "Trap", element: "Wasser", rarity: "Common", text: "Trigger: Wenn dein Gegner angreift. Effekt: Wähle eine angreifende Einheit. Ihr Angriff wird beendet und sie wird erschöpft.", img: "/cards/sudden-undertow.jpg", img_hint: "water whirl", previewVideoUrl: "/cards/videos/sudden-undertow.mp4" },
  { id: 31, set: SET_NAME, numberInSet: 31, totalInSet: TOTAL_IN_SET, name: "Frozen Lock", cost: 3, type: "Trap", element: "Wasser", rarity: "Epic", text: "Trigger: Wenn eine gegnerische Einheit ins Spiel kommt. Effekt: Diese Einheit kann weder angreifen noch blocken, bis zum Beginn des nächsten gegnerischen Zuges.", img: "/cards/frozen-lock.jpg", img_hint: "ice lock", previewVideoUrl: "/cards/videos/frozen-lock.mp4" },
  { id: 32, set: SET_NAME, numberInSet: 32, totalInSet: TOTAL_IN_SET, name: "Pearl of Stillness", cost: 2, type: "Relic", element: "Wasser", rarity: "Epic", text: "Der erste Spell, den dein Gegner in jedem Zug wirkt, kostet +[AETHER:1].", img: "/cards/pearl-of-stillness.jpg", img_hint: "glowing pearl", previewVideoUrl: "/cards/videos/pearl-of-stillness.mp4" },
  // =======================================================================
  // AETHER (NON-RESOURCE)
  // =======================================================================
  { id: 33, set: SET_NAME, numberInSet: 33, totalInSet: TOTAL_IN_SET, name: "Aether Initiate", cost: 1, type: "Unit", element: "Aether", rarity: "Common", atk: 1, hp: 2, fokus: 1, text: "Beim Ausspielen: Erhalte [AETHER:1].", img: "/cards/aether-initiate.jpg", img_hint: "aether acolyte", previewVideoUrl: "/cards/videos/aether-initiate.mp4" },
  { id: 34, set: SET_NAME, numberInSet: 34, totalInSet: TOTAL_IN_SET, name: "Flux Adept", cost: 2, type: "Unit", element: "Aether", rarity: "Rare", atk: 2, hp: 3, fokus: 2, text: "Immer wenn du Aether erhältst (außer durch reguläres Legen), ziehe 1 Karte. (Maximal 1× pro Zug.)", img: "/cards/flux-adept.jpg", img_hint: "flux mage", previewVideoUrl: "/cards/videos/flux-adept.mp4" },
  { id: 35, set: SET_NAME, numberInSet: 35, totalInSet: TOTAL_IN_SET, name: "Aether Channeler", cost: 3, type: "Unit", element: "Aether", rarity: "Uncommon", atk: 3, hp: 3, fokus: 3, text: "Aktiv (1 Fokus): Wähle: Erhalte [AETHER:1] ODER reduziere die Kosten des nächsten Spells, den du in diesem Zug wirkst, um 1.", img: "/cards/aether-channeler.jpg", img_hint: "aether channeler", previewVideoUrl: "/cards/videos/aether-channeler.mp4" },
  { id: 36, set: SET_NAME, numberInSet: 36, totalInSet: TOTAL_IN_SET, name: "Aether Guardian", cost: 4, type: "Unit", element: "Aether", rarity: "Rare", atk: 3, hp: 5, fokus: 1, text: "Solange Aether Guardian im Spiel ist, kosten gegnerische Spells +[AETHER:1].", img: "/cards/aether-guardian.jpg", img_hint: "aether guardian", previewVideoUrl: "/cards/videos/aether-guardian.mp4" },
  { id: 37, set: SET_NAME, numberInSet: 37, totalInSet: TOTAL_IN_SET, name: "Aether Titan", cost: 5, type: "Unit", element: "Aether", rarity: "Epic", atk: 4, hp: 5, fokus: 4, text: "Immer wenn ein Spieler einen Spell wirkt, erhältst du 1 Fokus auf Aether Titan.", img: "/cards/aether-titan.jpg", img_hint: "aether titan", previewVideoUrl: "/cards/videos/aether-titan.mp4" },
  { id: 38, set: SET_NAME, numberInSet: 38, totalInSet: TOTAL_IN_SET, name: "Sileth", cost: 5, type: "Unit", element: "Aether", rarity: "Epic", atk: 5, hp: 4, fokus: 1, text: "Beim Ausspielen: Verbanne eine gegnerische Einheit mit Kosten 3 oder weniger.", img: "/mission/sileth.jpg", img_hint: "shadow assassin", previewVideoUrl: "/mission/sileth.mp4" },
  { id: 39, set: SET_NAME, numberInSet: 39, totalInSet: TOTAL_IN_SET, name: "Kai", cost: 4, type: "Unit", element: "Aether", rarity: "Epic", atk: 4, hp: 4, fokus: 2, text: "Immer wenn du eine [AETHER:0] Aether-Karte legst, heile deinen Binder um 1 HP.", img: "/cards/kai.jpg", img_hint: "aether warrior", previewVideoUrl: "/cards/videos/kai.mp4" },
  { id: 40, set: SET_NAME, numberInSet: 40, totalInSet: TOTAL_IN_SET, name: "Aether Dragon", cost: 6, type: "Unit", element: "Aether", rarity: "Epic", atk: 5, hp: 6, fokus: 2, text: "Deine Spells kosten [AETHER:1] weniger (mindestens 1).", img: "/cards/aether-dragon.jpg", img_hint: "aether ascendant", previewVideoUrl: "/cards/videos/aether-dragon.mp4" },
  { id: 41, set: SET_NAME, numberInSet: 41, totalInSet: TOTAL_IN_SET, name: "Aurex", cost: 4, type: "Unit", element: "Aether", rarity: "Legendary", atk: 3, hp: 4, fokus: 4, text: "Passiv: Immer wenn eine Einheit stirbt, erhalte 1 Fokus auf Aurex. Aktiv (1 Fokus): Wähle: • Eine Einheit erhält –2 ATK. • Beschwöre 1/1 Schatten. Ultimate (4 Fokus): Zerstöre alle Einheiten mit Kosten ≤3. Du erhältst 1 HP pro Einheit.", img: "/mission/aurex.jpg", img_hint: "cosmic entity", previewVideoUrl: "/mission/aurex.mp4" },
  { id: 42, set: SET_NAME, numberInSet: 42, totalInSet: TOTAL_IN_SET, name: "Aether Shift", cost: 1, type: "Spell", element: "Aether", rarity: "Common", text: "Tausche die Aether-Kosten von zwei Einheiten bis zum Ende des Zuges.", img: "/cards/aether-shift.jpg", img_hint: "aether shift", previewVideoUrl: "/cards/videos/aether-shift.mp4" },
  { id: 43, set: SET_NAME, numberInSet: 43, totalInSet: TOTAL_IN_SET, name: "Fifth Portal", cost: 1, type: "Spell", element: "Aether", rarity: "Common", text: "Erhalte [AETHER:2].", img: "/cards/fifth-portal.jpg", img_hint: "aether surge", previewVideoUrl: "/cards/videos/fifth-portal.mp4" },
  { id: 44, set: SET_NAME, numberInSet: 44, totalInSet: TOTAL_IN_SET, name: "Aether Breath", cost: 4, type: "Spell", element: "Aether", rarity: "Rare", text: "Zerstöre alle gebundenen Einheiten (Einheiten mit aktiven Effekten oder Ausrüstung).", img: "/cards/aether-breath.jpg", img_hint: "chain break", previewVideoUrl: "/cards/videos/aether-breath.mp4" },
  { id: 45, set: SET_NAME, numberInSet: 45, totalInSet: TOTAL_IN_SET, name: "Rewrite Fate", cost: 5, type: "Spell", element: "Aether", rarity: "Legendary", text: "Setze alle Einheiten auf dem Feld in ihren Grundzustand zurück (stellt HP wieder her, entfernt alle Effekte und Relikte).", img: "/cards/rewrite-fate.jpg", img_hint: "time reverse", previewVideoUrl: "/cards/videos/rewrite-fate.mp4" },
  { id: 46, set: SET_NAME, numberInSet: 46, totalInSet: TOTAL_IN_SET, name: "Aether Drain", cost: 2, type: "Spell", element: "Aether", rarity: "Common", text: "Dein Aether-Vorrat wird für diesen Zug auf den aktuellen Aether-Vorrat deines Gegners gesetzt.", img: "/cards/aether-drain.jpg", img_hint: "aether drain", previewVideoUrl: "/cards/videos/aether-drain.mp4" },
  { id: 47, set: SET_NAME, numberInSet: 47, totalInSet: TOTAL_IN_SET, name: "Temporal Chamber", cost: 3, type: "Trap", element: "Aether", rarity: "Rare", text: "Trigger: Wenn eine Einheit angreift. Effekt: Beende den Angriff. Diese Einheit überspringt ihren nächsten Zug.", img: "/cards/temporal-chamber.jpg", img_hint: "time trap", previewVideoUrl: "/cards/videos/temporal-chamber.mp4" },
  { id: 48, set: SET_NAME, numberInSet: 48, totalInSet: TOTAL_IN_SET, name: "Echo of Aether", cost: 2, type: "Trap", element: "Aether", rarity: "Epic", text: "Trigger: Wenn ein gegnerischer Spell aktiviert wird. Effekt: Kopiere diesen Spell. Du wählst neue Ziele für die Kopie.", img: "/cards/echo-of-aether.jpg", img_hint: "magic copy", previewVideoUrl: "/cards/videos/echo-of-aether.mp4" },
  { id: 49, set: SET_NAME, numberInSet: 49, totalInSet: TOTAL_IN_SET, name: "Aether Crown", cost: 2, type: "Relic", element: "Aether", rarity: "Epic", text: "Einmal pro Zug: Erhalte [AETHER:1], wenn du keinen Aether gelegt hast.", img: "/cards/aether-crown.jpg", img_hint: "aether crown", previewVideoUrl: "/cards/videos/aether-crown.mp4" },
  // =======================================================================
  // ERDE
  // =======================================================================
  { id: 50, set: SET_NAME, numberInSet: 50, totalInSet: TOTAL_IN_SET, name: "Seedling Swarm", cost: 1, type: "Unit", element: "Erde", rarity: "Uncommon", atk: 1, hp: 2, fokus: 1, text: "Beim Ausspielen: Beschwöre einen 1/1 Parasiten. Einheiten, die auf den Parasiten gespielt werden, erhalten +1/+1.", img: "/cards/seedling-swarm.jpg", img_hint: "plant swarm", previewVideoUrl: "/cards/videos/seedling-swarm.mp4" },
  { id: 51, set: SET_NAME, numberInSet: 51, totalInSet: TOTAL_IN_SET, name: "Grove Stalker", cost: 2, type: "Unit", element: "Erde", rarity: "Common", atk: 2, hp: 2, fokus: 1, text: "Wenn Grove Stalker angreift, erhalte 1 Fokus.", img: "/cards/grove-stalker.jpg", img_hint: "jungle stalker", previewVideoUrl: "/cards/videos/grove-stalker.mp4" },
  { id: 52, set: SET_NAME, numberInSet: 52, totalInSet: TOTAL_IN_SET, name: "Lifebloom Druid", cost: 2, type: "Unit", element: "Erde", rarity: "Common", atk: 2, hp: 3, fokus: 2, text: "Beim Ausspielen: Heile deinen Binder um 2 HP.", img: "/cards/lifebloom-druid.jpg", img_hint: "nature druid", previewVideoUrl: "/cards/videos/lifebloom-druid.mp4" },
  { id: 53, set: SET_NAME, numberInSet: 53, totalInSet: TOTAL_IN_SET, name: "Verdant Warden", cost: 3, type: "Unit", element: "Erde", rarity: "Rare", atk: 3, hp: 5, fokus: 1, text: "Solange Verdant Warden im Spiel ist, erhalten deine Units +1 HP.", img: "/cards/verdant-warden.jpg", img_hint: "forest warden", previewVideoUrl: "/cards/videos/verdant-warden.mp4" },
  { id: 54, set: SET_NAME, numberInSet: 54, totalInSet: TOTAL_IN_SET, name: "Golem", cost: 4, type: "Unit", element: "Erde", rarity: "Rare", atk: 4, hp: 4, fokus: 2, text: "Immer wenn du heilst, erhält Golem +1 Angriff.", img: "/cards/golem.jpg", img_hint: "wild champion", previewVideoUrl: "/cards/videos/golem.mp4" },
  { id: 55, set: SET_NAME, numberInSet: 55, totalInSet: TOTAL_IN_SET, name: "Behemoth", cost: 4, type: "Unit", element: "Erde", rarity: "Rare", atk: 3, hp: 6, fokus: 1, text: "Behemoth erhält –1 Schaden aus allen Quellen.", img: "/cards/behemoth.jpg", img_hint: "behemoth monster", previewVideoUrl: "/cards/videos/behemoth.mp4" },
  { id: 56, set: SET_NAME, numberInSet: 56, totalInSet: TOTAL_IN_SET, name: "Obryn", cost: 5, type: "Unit", element: "Erde", rarity: "Legendary", atk: 5, hp: 5, fokus: 2, text: "Wenn Obryn angreift, füge allen gegnerischen Units 1 Schaden zu.", img: "/mission/obryn.jpg", img_hint: "stone titan", previewVideoUrl: "/mission/obryn.mp4" },
  { id: 57, set: SET_NAME, numberInSet: 57, totalInSet: TOTAL_IN_SET, name: "Ancient Treant", cost: 6, type: "Unit", element: "Erde", rarity: "Epic", atk: 6, hp: 7, fokus: 2, text: "Zu Beginn deines Zuges: Heile deinen Binder um 2.", img: "/cards/ancient-treant.jpg", img_hint: "ancient tree", previewVideoUrl: "/cards/videos/ancient-treant.mp4" },
  { id: 58, set: SET_NAME, numberInSet: 58, totalInSet: TOTAL_IN_SET, name: "Regrowth", cost: 2, type: "Spell", element: "Erde", rarity: "Common", text: "Heile deinen Binder um 3. Ziehe 1 Karte.", img: "/cards/regrowth.jpg", img_hint: "nature heal", previewVideoUrl: "/cards/videos/regrowth.mp4" },
  { id: 59, set: SET_NAME, numberInSet: 59, totalInSet: TOTAL_IN_SET, name: "Entangling Roots", cost: 2, type: "Spell", element: "Erde", rarity: "Common", text: "Eine gegnerische Unit wird gefesselt (kann in diesem Zug nicht angreifen oder blocken).", img: "/cards/entangling-roots.jpg", img_hint: "entangling roots", previewVideoUrl: "/cards/videos/entangling-roots.mp4" },
  { id: 60, set: SET_NAME, numberInSet: 60, totalInSet: TOTAL_IN_SET, name: "Verdant Surge", cost: 3, type: "Spell", element: "Erde", rarity: "Common", text: "Eine Unit erhält +2 Angriff und +2 HP bis zum Ende des Zuges.", img: "/cards/verdant-surge.jpg", img_hint: "nature growth", previewVideoUrl: "/cards/videos/verdant-surge.mp4" },
  { id: 61, set: SET_NAME, numberInSet: 61, totalInSet: TOTAL_IN_SET, name: "Nature's Balance", cost: 4, type: "Spell", element: "Erde", rarity: "Rare", text: "Setze den Angriff aller Units auf 3 bis zum Ende des Zuges.", img: "/cards/natures-balance.jpg", img_hint: "nature balance", previewVideoUrl: "/cards/videos/natures-balance.mp4" },
  { id: 62, set: SET_NAME, numberInSet: 62, totalInSet: TOTAL_IN_SET, name: "Thorn Snare", cost: 2, type: "Trap", element: "Erde", rarity: "Common", text: "Trigger: Wenn eine gegnerische Unit angreift. Effekt: Beende den Angriff. Die Unit erhält 2 Schaden.", img: "/cards/thorn-snare.jpg", img_hint: "thorn trap", previewVideoUrl: "/cards/videos/thorn-snare.mp4" },
  { id: 63, set: SET_NAME, numberInSet: 63, totalInSet: TOTAL_IN_SET, name: "Natural Retaliation", cost: 3, type: "Trap", element: "Erde", rarity: "Rare", text: "Trigger: Wenn eine deiner Units stirbt. Effekt: Füge einer gegnerischen Unit 3 Schaden zu.", img: "/cards/natural-retaliation.jpg", previewVideoUrl: "/cards/videos/natural-retaliation.mp4" },
  { id: 64, set: SET_NAME, numberInSet: 64, totalInSet: TOTAL_IN_SET, name: "Thorn Crown", cost: 3, type: "Relic", element: "Erde", rarity: "Epic", text: "Immer wenn du heilst, erhalte 1 Fokus auf eine zufällige befreundete Unit.", img: "/cards/thorn-crown.jpg", img_hint: "thorn crown", previewVideoUrl: "/cards/videos/thorn-crown.mp4" },
  // =======================================================================
  // LUFT
  // =======================================================================
  { id: 65, set: SET_NAME, numberInSet: 65, totalInSet: TOTAL_IN_SET, name: "Sparkblade Rogue", cost: 1, type: "Unit", element: "Luft", rarity: "Common", atk: 2, hp: 1, fokus: 1, text: "Sparkblade Rogue kann im Zug des Ausspielens angreifen.", img: "/cards/sparkblade-rogue.jpg", img_hint: "fast rogue", previewVideoUrl: "/cards/videos/sparkblade-rouge.mp4" },
  { id: 66, set: SET_NAME, numberInSet: 66, totalInSet: TOTAL_IN_SET, name: "Storm Elementar", cost: 2, type: "Unit", element: "Luft", rarity: "Common", atk: 2, hp: 3, fokus: 2, text: "Immer wenn du einen Spell wirkst, erhalte 1 Fokus.", img: "/cards/storm-elementar.jpg", img_hint: "volt mage", previewVideoUrl: "/cards/videos/storm-elementar.mp4" },
  { id: 67, set: SET_NAME, numberInSet: 67, totalInSet: TOTAL_IN_SET, name: "Stormrunner", cost: 2, type: "Unit", element: "Luft", rarity: "Uncommon", atk: 3, hp: 2, fokus: 1, text: "Stormrunner kann nicht geblockt werden von Units mit Kosten 3 oder weniger.", img: "/cards/stormrunner.jpg", img_hint: "storm runner", previewVideoUrl: "/cards/videos/stormrunner.mp4" },
  { id: 68, set: SET_NAME, numberInSet: 68, totalInSet: TOTAL_IN_SET, name: "Kira", cost: 4, type: "Unit", element: "Luft", rarity: "Epic", atk: 3, hp: 3, fokus: 2, text: "Beim Angriff: Kira greift zweimal an.", img: "/cards/kira.jpg", img_hint: "female swordmaster", previewVideoUrl: "/cards/videos/kira.mp4" },
  { id: 69, set: SET_NAME, numberInSet: 69, totalInSet: TOTAL_IN_SET, name: "Chainblade Adept", cost: 3, type: "Unit", element: "Luft", rarity: "Rare", atk: 3, hp: 2, fokus: 2, text: "Immer wenn Chainblade Adept Schaden verursacht, füge einem anderen Ziel 1 Schaden zu.", img: "/cards/chainblade-adept.jpg", img_hint: "chainblade fighter", previewVideoUrl: "/cards/videos/chainblade-adept.mp4" },
  { id: 70, set: SET_NAME, numberInSet: 70, totalInSet: TOTAL_IN_SET, name: "Arc Striker", cost: 4, type: "Unit", element: "Luft", rarity: "Epic", atk: 4, hp: 3, fokus: 1, text: "Beim Ausspielen: Füge einem Ziel 2 Schaden zu.", img: "/cards/arc-striker.jpg", img_hint: "arc striker", previewVideoUrl: "/cards/videos/arc-striker.mp4" },
  { id: 71, set: SET_NAME, numberInSet: 71, totalInSet: TOTAL_IN_SET, name: "AERION", cost: 6, type: "Unit", element: "Luft", rarity: "Legendary", atk: 6, hp: 5, fokus: 2, text: "Beim Angriff: Füge dem gegnerischen Binder 3 Schaden zu.", img: "/mission/aerion.jpg", img_hint: "sky warrior", previewVideoUrl: "/mission/aerion.mp4" },
  { id: 72, set: SET_NAME, numberInSet: 72, totalInSet: TOTAL_IN_SET, name: "Lightning Bolt", cost: 1, type: "Spell", element: "Luft", rarity: "Common", text: "Füge einem Ziel 2 Schaden zu.", img: "/cards/lightning-bolt.jpg", img_hint: "lightning bolt", previewVideoUrl: "/cards/videos/lightning-bolt.mp4" },
  { id: 73, set: SET_NAME, numberInSet: 73, totalInSet: TOTAL_IN_SET, name: "Air Temple", cost: 2, type: "Spell", element: "Luft", rarity: "Common", text: "Deine nächste Unit in diesem Zug erhält +1 Angriff und kann sofort angreifen.", img: "/cards/air-temple.jpg", img_hint: "static electricity", previewVideoUrl: "/cards/videos/air-temple.mp4" },
  { id: 74, set: SET_NAME, numberInSet: 74, totalInSet: TOTAL_IN_SET, name: "Chain Lightning", cost: 3, type: "Spell", element: "Luft", rarity: "Rare", text: "Füge bis zu 3 verschiedenen Zielen jeweils 2 Schaden zu.", img: "/cards/chain-lightning.jpg", img_hint: "chain lightning", previewVideoUrl: "/cards/videos/chain-lightning.mp4" },
  { id: 75, set: SET_NAME, numberInSet: 75, totalInSet: TOTAL_IN_SET, name: "Protective Wind", cost: 2, type: "Spell", element: "Luft", rarity: "Common", text: "Eine deiner Units vermeidet allen Schaden in diesem Zug.", img: "/cards/protective-wind.jpg", img_hint: "fast step", previewVideoUrl: "/cards/videos/protective-wind.mp4" },
  { id: 76, set: SET_NAME, numberInSet: 76, totalInSet: TOTAL_IN_SET, name: "Airstrike", cost: 4, type: "Spell", element: "Luft", rarity: "Rare", text: "Füge allen gegnerischen Units 2 Schaden zu.", img: "/cards/airstrike.jpg", img_hint: "thunder storm", previewVideoUrl: "/cards/videos/airstrike.mp4" },
  { id: 77, set: SET_NAME, numberInSet: 77, totalInSet: TOTAL_IN_SET, name: "Static Trap", cost: 2, type: "Trap", element: "Luft", rarity: "Common", text: "Trigger: Wenn ein Spell aktiviert wird. Effekt: Füge dem auslösenden Spieler 2 Schaden zu.", img: "/cards/static-trap.jpg", img_hint: "static trap", previewVideoUrl: "/cards/videos/static-trap.mp4" },
  { id: 78, set: SET_NAME, numberInSet: 78, totalInSet: TOTAL_IN_SET, name: "Sandstrom", cost: 3, type: "Trap", element: "Luft", rarity: "Rare", text: "Trigger: Wenn dein Binder Schaden erleiden würde. Effekt: Verhindere diesen Schaden.", img: "/cards/sandstorm.jpg", img_hint: "light barrier", previewVideoUrl: "/cards/videos/sandstorm.mp4" },
  { id: 79, set: SET_NAME, numberInSet: 79, totalInSet: TOTAL_IN_SET, name: "Storm Crown", cost: 2, type: "Relic", element: "Luft", rarity: "Epic", text: "Die erste Unit, die du in jedem Zug spielst, kostet [AETHER:1] weniger.", img: "/cards/storm-crown.jpg", img_hint: "speed core", previewVideoUrl: "/cards/videos/storm-crown.mp4" },
  // =======================================================================
  // AETHER RESOURCES
  // =======================================================================
  { id: 80, set: SET_NAME, numberInSet: 80, totalInSet: TOTAL_IN_SET, name: "Aether Source", cost: 0, type: "Aether", element: "Aether", rarity: "Common", text: "Max. 1 Aether pro Zug. Erzeugt 1 Aether.", img: "/cards/aether-source.jpg", img_hint: "aether crystal", previewVideoUrl: "/cards/videos/aether-source.mp4" },
  { id: 81, set: SET_NAME, numberInSet: 81, totalInSet: TOTAL_IN_SET, name: "Bound Aether", cost: 0, type: "Aether", element: "Aether", rarity: "Uncommon", text: "Max. 1 Aether pro Zug. Erzeugt 1 Aether. Wenn du in diesem Zug eine Unit ausspielst, erhält diese +1 Fokus.", img: "/cards/bound-aether.jpg", img_hint: "bound energy", previewVideoUrl: "/cards/videos/bound-aether.mp4" },
  { id: 82, set: SET_NAME, numberInSet: 82, totalInSet: TOTAL_IN_SET, name: "Aether Potion", cost: 0, type: "Aether", element: "Aether", rarity: "Uncommon", text: "Max. 1 Aether pro Zug. Erzeugt 1 Aether. Wenn du keine Units kontrollierst, erzeuge stattdessen 2 Aether.", img: "/cards/aether-potion.jpg", img_hint: "aether potion", previewVideoUrl: "/cards/videos/aether-potion.mp4" },
  { id: 83, set: SET_NAME, numberInSet: 83, totalInSet: TOTAL_IN_SET, name: "Aether Cave", cost: 0, type: "Aether", element: "Aether", rarity: "Uncommon", text: "Max. 1 Aether pro Zug. Erzeugt 1 Aether. Beim Bezahlen von Overcharge zählt diese Karte als 2 Aether.", img: "/cards/aether-cave.jpg", img_hint: "surging power", previewVideoUrl: "/cards/videos/aether-cave.mp4" },
  { id: 84, set: SET_NAME, numberInSet: 84, totalInSet: TOTAL_IN_SET, name: "Disruptive Aether", cost: 0, type: "Aether", element: "Aether", rarity: "Rare", text: "Max. 1 Aether pro Zug. Erzeugt 1 Aether. Einmal pro Zug: Der nächste gegnerische Spell kostet +[AETHER:1] (Nicht stapelbar).", img: "/cards/disruptive-aether.jpg", img_hint: "disruptive energy", previewVideoUrl: "/cards/videos/disruptive-aether.mp4" },
  { id: 85, set: SET_NAME, numberInSet: 85, totalInSet: TOTAL_IN_SET, name: "Ascended Aether", cost: 0, type: "Aether", element: "Aether", rarity: "Rare", text: "Max. 1 Aether pro Zug. Erzeugt 1 Aether. Wenn du 4 oder mehr andere Aether kontrollierst, erzeuge stattdessen 2 Aether.", img: "/cards/ascended-aether.jpg", img_hint: "ascended power", previewVideoUrl: "/cards/videos/ascended-aether.mp4" },
  { id: 86, set: SET_NAME, numberInSet: 86, totalInSet: TOTAL_IN_SET, name: "Aether Core", cost: 0, type: "Aether", element: "Aether", rarity: "Epic", text: "Max. 1 Aether pro Zug. Erzeugt 1 Aether. Immer wenn dein Gegner Aether erhält (außer durch Legen), verliert er 1 Binder-HP.", img: "/cards/aether-core.jpg", img_hint: "draining life", previewVideoUrl: "/cards/videos/aether-core.mp4" },
  { id: 87, set: SET_NAME, numberInSet: 87, totalInSet: TOTAL_IN_SET, name: "Aether Reactor", cost: 0, type: "Aether", element: "Aether", rarity: "Epic", text: "Einmal pro Spiel: Erzeuge [AETHER:3]. Danach kannst du in diesem Zug weder Zauber wirken noch angreifen.", img: "/cards/aether-reactor.jpg", img_hint: "fractured power", previewVideoUrl: "/cards/videos/aether-reactor.mp4" },
  { id: 88, set: SET_NAME, numberInSet: 88, totalInSet: TOTAL_IN_SET, name: "Aether Oasis", cost: 0, type: "Aether", element: "Aether", rarity: "Legendary", text: "Max. 1 pro Deck. Erzeugt 1 Aether. Zu Beginn deines Zuges: Erhalte +1 Aether, der dein Maximum überschreiten kann.", img: "/cards/aether-oasis.jpg", img_hint: "primordial core", previewVideoUrl: "/cards/videos/aether-oasis.mp4" },
  { id: 89, set: SET_NAME, numberInSet: 89, totalInSet: TOTAL_IN_SET, name: "Aether Spirit", cost: 0, type: "Aether", element: "Aether", rarity: "Legendary", text: "Max. 1 Aether pro Zug. Erzeugt 1 Aether. Einmal pro Spiel: Erzeuge [AETHER:3]. Danach kannst du in diesem Zug weder Zauber wirken noch angreifen.", img: "/cards/aether-spirit.jpg", img_hint: "aether spirit", previewVideoUrl: "/cards/videos/aether-spirit.mp4" },
  // =======================================================================
  // GOD CARD
  // =======================================================================
  { id: 90, set: SET_NAME, numberInSet: 90, totalInSet: TOTAL_IN_SET, name: "Aether Spirit GOD", cost: 0, type: "Aether", element: "Aether", rarity: "GOD", text: "Max. 1 Aether pro Zug. Erzeugt 1 Aether. Einmal pro Spiel: Erzeuge [AETHER:3]. Danach kannst du in diesem Zug weder Zauber wirken noch angreifen.", img: "/cards/aether-spirit-god.jpg", overlay_img: "/cards/aether-spirit-god-overlay.png", default_img: "/cards/aether-spirit-god-default.png", img_hint: "god spirit" },
  // =======================================================================
  // TOKENS
  // =======================================================================
  { id: 998, set: "TOKEN", numberInSet: 2, totalInSet: 2, name: "Schatten", cost: 1, type: "Unit", element: "Aether", rarity: "Common", atk: 1, hp: 1, fokus: 0, text: "Eine flüchtige Erscheinung aus reiner Schattenenergie.", img: "/cards/ashwalker.jpg", img_hint: "shadow creature" },
  { id: 999, set: "TOKEN", numberInSet: 1, totalInSet: 1, name: "Parasit", cost: 1, type: "Unit", element: "Erde", rarity: "Common", atk: 1, hp: 1, fokus: 0, text: "Kann geopfert werden, um eine andere Einheit zu spielen. Die neue Einheit erhält +1/+1.", img: "/cards/parasit.jpg", img_hint: "alien parasite" },
];
